### PR TITLE
Update LanguageServer submodule to v1.0.0 and SymbolServer to v1.0.1

### PR DESCRIPTION
**Pull request by AlexLewandowski**
This will at least allow the LanguageServer to work with Julia 1.3

### CODE REVIEW

**Comment by gdkrmr** [comment]
Works for me, thank you! How did you pick the submodule versions? They are almost all different from the latest tags/master from julia-vscode/julia-vscode.

EDIT: Doesn't work for julia 1.0 any more, this should be mentioned somewhere.

**Comment by AlexLewandowski** [comment]
I just used the [deps] in Project.toml for LanguageServer#v1.0.0. 

Are you sure you set `(setq lsp-julia-default-environment "~/.julia/environments/v1.0")`? I was able to get it to work with Julia v1.0.5 (current LTS).

**Comment by gdkrmr** [comment]
I unset `lsp-julia-default-environmnet`. I will have to try again then.

**Comment by AlexLewandowski** [comment]
Whoops, my mistake! The reason this was working on Julia v1.0 was due to the following (monkey-) patch for Julia v1.4.

```
diff --git a/src/symbols.jl b/src/symbols.jl
index f74f85c..1b2dc1a 100644
--- a/src/symbols.jl
+++ b/src/symbols.jl
@@ -212,7 +212,7 @@ function cache_package(c::Pkg.Types.Context, uuid::UUID, depot::Dict, env_path =
         if path(pe) isa String
             env_path = path(pe)
             Pkg.API.activate(env_path)
-        elseif !is_stdlib(c, uuid) && ((Pkg.API.dir(pe_name) isa String) && !isempty(Pkg.API.dir(pe_name)))
+        elseif ((Pkg.API.dir(pe_name) isa String) && !isempty(Pkg.API.dir(pe_name)))
             env_path = Pkg.API.dir(pe_name)
             Pkg.API.activate(env_path)
         end
```

Perhaps we can compile backports and fixes until LanguageServer.jl is running properly on v2.0.0?

**Comment by gdkrmr** [comment]
Feel free to do it, I currently don't have the capacity to do anything more complex than the current `lsp-julia`.

**Pull request merged**
