### PR TITLE
Add use-package install to README

### PR DESCRIPTION
**Pull request by ordicker**
Hi I just added use-package install to the README file. I think that's helpful.

BTW I think you sure bump the release version to 0.3 (I know there is a 0.3v branch but the Releases tab on the right is showing 0.2)

### CODE REVIEW

**Comment by gdkrmr** [comment]
Thanks!

**Comment by ordicker** [comment]
No, thank you! I was really close to leave Emacs for Vscode for julia development. you saved me. 

BTW, do you want to add tests and CI to the package? I was thinking about adding [makem](https://github.com/alphapapa/makem.sh) and Github actions. What do you think?

**Comment by gdkrmr** [comment]
It is not quite clear to me how CI would work on this package. If you have an idea I am happy to accept a PR!

**Comment by ordicker** [comment]
Well from what I experienced in the last year, this package suffers from bugs(or miss features) in lsp-mode and LanguageServer.jl. 
So I think to check in the CI the matrix versions of: 
emacs
lsp-mode
LanguageServer
julia-mode 
So if we detect a bug we could report it early. Is it makes sense? 
I didn't use makem but I try to mess with it and make a PR.

**Comment by gdkrmr** [comment]
That would be great!

**Comment by ordicker** [comment]
Hi, I start working on that ([fork](https://github.com/ordicker/lsp-julia) ). 
Do you know any way to make sure that the language server is up? with elisp for testing

And I'm not sure how the tests are passing, because I check for julia cmd to be present and I didn't configure it on the yml file :man_shrugging:

**Comment by fleimgruber** [comment]
@ordicker I would like to help test this, so it would be good if you could open an issue and a matching pull request for this new CI activity to discuss your progress.

**Pull request merged**
